export const coursesData = [
  {
    id: 1,
    title: "SSC Staff Selection Commission Course",
    description: "Comprehensive preparation for SSC CGL, CDS, GD, JE, CHSL, MTS, and other Examination.",
    image: "/img/course.jpg",
    category: "UPSC", 
    rating: 4.9,
    students: Math.floor(Math.random() * (500 - 50 + 1)) + 50,
    duration: "12 months",
    lessons: 240,
    price: 750,
    popular: true
  },
  {
    id: 2,
    title: "Banking Exams Master Course",
    description: "Complete preparation for SBI, IBPS, RBI and other banking examinations.",
    image: "/img/course.jpg",
    category: "Banking",
    rating: 4.8,
    students: Math.floor(Math.random() * (500 - 50 + 1)) + 50,
    duration: "6 months",
    lessons: 180,
    price: 600,
    popular: false
  },
  {
    id: 3,
    title: "RAILWAY RECRUITMENT EXAMINATIONS",
    description: "Structured course for RRB NTPC, RRB ALP, RRB JE, RRB GROUP D, with mock tests.",
    image: "/img/course.jpg",
    category: "SSC", 
    rating: 4.7,
    students: Math.floor(Math.random() * (500 - 50 + 1)) + 50,
    duration: "8 months",
    lessons: 200,
    price: 900,
    popular: true
  },
  {
    id: 4,
    title: "STATE LEVEL EXAMS Computer Science",
    description: "In-depth preparation for STATE LEVEL EXAMS CS with focus on core concepts and problem solving.",
    image: "/img/course.jpg",
    category: "GATE", 
    rating: 4.9,
    students: Math.floor(Math.random() * (500 - 50 + 1)) + 50,
    duration: "10 months",
    lessons: 220,
    price: 1100,
    popular: false
  },
  {
    id: 5,
    title: "SSC Prelims Test Series",
    description: "Extensive test series with detailed solutions and performance analytics.",
    image: "/img/course.jpg",
    category: "UPSC", 
    rating: 4.8,
    students: Math.floor(Math.random() * (500 - 50 + 1)) + 50,
    duration: "4 months",
    lessons: 60,
    price: 550,
    popular: false
  },
  {
    id: 6,
    title: "RAILWAY targated batch",
    description: "Comprehensive preparation RRB NTPC & RRB GROUP D",
    image: "/img/course.jpg",
    category: "SSC", 
    rating: 4.6,
    students: Math.floor(Math.random() * (500 - 50 + 1)) + 50,
    duration: "6 months",
    lessons: 150,
    price: 800,
    popular: false
  },
  {
    id: 7,
    title: "IBPS PO & Clerk Combo",
    description: "Combined preparation for IBPS PO and Clerk examinations with specialized focus.",
    image: "/img/course.jpg",
    category: "Banking",
    rating: 4.7,
    students: Math.floor(Math.random() * (500 - 50 + 1)) + 50,
    duration: "8 months",
    lessons: 190,
    price: 950,
    popular: true
  },
  {
    id: 8,
    title: "STATE LEVEL EXAMS Mechanical Engineering",
    description: "Complete preparation for STATE LEVEL EXAMS ME with subject experts and solved papers.",
    image: "/img/course.jpg",
    category: "GATE", 
    rating: 4.8,
    students: Math.floor(Math.random() * (500 - 50 + 1)) + 50,
    duration: "10 months",
    lessons: 210,
    price: 1150,
    popular: false
  }
];
